// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApexCustomersColumns holds the columns for the "apex_customers" table.
	ApexCustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "event_raised_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "given_name", Type: field.TypeString, Nullable: true},
		{Name: "middle_name", Type: field.TypeString, Nullable: true},
		{Name: "family_name", Type: field.TypeString, Nullable: true},
		{Name: "photo_url", Type: field.TypeString, Nullable: true},
		{Name: "photo_url_24", Type: field.TypeString, Nullable: true},
		{Name: "photo_url_32", Type: field.TypeString, Nullable: true},
		{Name: "photo_url_48", Type: field.TypeString, Nullable: true},
		{Name: "photo_url_72", Type: field.TypeString, Nullable: true},
		{Name: "photo_url_192", Type: field.TypeString, Nullable: true},
		{Name: "photo_url_512", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// ApexCustomersTable holds the schema information for the "apex_customers" table.
	ApexCustomersTable = &schema.Table{
		Name:       "apex_customers",
		Columns:    ApexCustomersColumns,
		PrimaryKey: []*schema.Column{ApexCustomersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apexcustomer_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{ApexCustomersColumns[15]},
			},
		},
	}
	// ApexCustomerIdentitiesColumns holds the columns for the "apex_customer_identities" table.
	ApexCustomerIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "email_verified", Type: field.TypeBool, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "modified_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "apex_customer_identities", Type: field.TypeString},
	}
	// ApexCustomerIdentitiesTable holds the schema information for the "apex_customer_identities" table.
	ApexCustomerIdentitiesTable = &schema.Table{
		Name:       "apex_customer_identities",
		Columns:    ApexCustomerIdentitiesColumns,
		PrimaryKey: []*schema.Column{ApexCustomerIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "apex_customer_identities_apex_customers_identities",
				Columns:    []*schema.Column{ApexCustomerIdentitiesColumns[6]},
				RefColumns: []*schema.Column{ApexCustomersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apexcustomeridentity_email",
				Unique:  false,
				Columns: []*schema.Column{ApexCustomerIdentitiesColumns[1]},
			},
			{
				Name:    "apexcustomeridentity_email_verified",
				Unique:  false,
				Columns: []*schema.Column{ApexCustomerIdentitiesColumns[2]},
			},
			{
				Name:    "apexcustomeridentity_apex_customer_identities",
				Unique:  false,
				Columns: []*schema.Column{ApexCustomerIdentitiesColumns[6]},
			},
			{
				Name:    "apexcustomeridentity_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{ApexCustomerIdentitiesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApexCustomersTable,
		ApexCustomerIdentitiesTable,
	}
)

func init() {
	ApexCustomerIdentitiesTable.ForeignKeys[0].RefTable = ApexCustomersTable
}
