openapi: 3.1.0
info:
  title: Customer Processor v1
  description: "Customer Processor"
  version: 1.0.0

paths:
  /customer-processor/api/v1/liveness:
    get:
      tags:
        - customer
        - processor
      summary: return the health status
      operationId: liveness

      responses:
        "200":
          description: the health status

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /customer-processor/api/v1/readiness:
    get:
      tags:
        - customer
        - processor
      summary: return the readiness status
      operationId: readiness

      responses:
        "200":
          description: the readiness status

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
