// Code generated by ent, DO NOT EDIT.

package entities

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sigmasee/sigmasee/apex/shared/entities/apexcustomer"
	"github.com/sigmasee/sigmasee/apex/shared/entities/apexcustomeridentity"
	"github.com/sigmasee/sigmasee/apex/shared/entities/predicate"

	"github.com/sigmasee/sigmasee/apex/shared/entities/internal"
)

// ApexCustomerQuery is the builder for querying ApexCustomer entities.
type ApexCustomerQuery struct {
	config
	ctx                 *QueryContext
	order               []apexcustomer.OrderOption
	inters              []Interceptor
	predicates          []predicate.ApexCustomer
	withIdentities      *ApexCustomerIdentityQuery
	loadTotal           []func(context.Context, []*ApexCustomer) error
	modifiers           []func(*sql.Selector)
	withNamedIdentities map[string]*ApexCustomerIdentityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApexCustomerQuery builder.
func (acq *ApexCustomerQuery) Where(ps ...predicate.ApexCustomer) *ApexCustomerQuery {
	acq.predicates = append(acq.predicates, ps...)
	return acq
}

// Limit the number of records to be returned by this query.
func (acq *ApexCustomerQuery) Limit(limit int) *ApexCustomerQuery {
	acq.ctx.Limit = &limit
	return acq
}

// Offset to start from.
func (acq *ApexCustomerQuery) Offset(offset int) *ApexCustomerQuery {
	acq.ctx.Offset = &offset
	return acq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (acq *ApexCustomerQuery) Unique(unique bool) *ApexCustomerQuery {
	acq.ctx.Unique = &unique
	return acq
}

// Order specifies how the records should be ordered.
func (acq *ApexCustomerQuery) Order(o ...apexcustomer.OrderOption) *ApexCustomerQuery {
	acq.order = append(acq.order, o...)
	return acq
}

// QueryIdentities chains the current query on the "identities" edge.
func (acq *ApexCustomerQuery) QueryIdentities() *ApexCustomerIdentityQuery {
	query := (&ApexCustomerIdentityClient{config: acq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := acq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := acq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(apexcustomer.Table, apexcustomer.FieldID, selector),
			sqlgraph.To(apexcustomeridentity.Table, apexcustomeridentity.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, apexcustomer.IdentitiesTable, apexcustomer.IdentitiesColumn),
		)
		schemaConfig := acq.schemaConfig
		step.To.Schema = schemaConfig.ApexCustomerIdentity
		step.Edge.Schema = schemaConfig.ApexCustomerIdentity
		fromU = sqlgraph.SetNeighbors(acq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ApexCustomer entity from the query.
// Returns a *NotFoundError when no ApexCustomer was found.
func (acq *ApexCustomerQuery) First(ctx context.Context) (*ApexCustomer, error) {
	nodes, err := acq.Limit(1).All(setContextOp(ctx, acq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apexcustomer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (acq *ApexCustomerQuery) FirstX(ctx context.Context) *ApexCustomer {
	node, err := acq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApexCustomer ID from the query.
// Returns a *NotFoundError when no ApexCustomer ID was found.
func (acq *ApexCustomerQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = acq.Limit(1).IDs(setContextOp(ctx, acq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apexcustomer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (acq *ApexCustomerQuery) FirstIDX(ctx context.Context) string {
	id, err := acq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApexCustomer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApexCustomer entity is found.
// Returns a *NotFoundError when no ApexCustomer entities are found.
func (acq *ApexCustomerQuery) Only(ctx context.Context) (*ApexCustomer, error) {
	nodes, err := acq.Limit(2).All(setContextOp(ctx, acq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apexcustomer.Label}
	default:
		return nil, &NotSingularError{apexcustomer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (acq *ApexCustomerQuery) OnlyX(ctx context.Context) *ApexCustomer {
	node, err := acq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApexCustomer ID in the query.
// Returns a *NotSingularError when more than one ApexCustomer ID is found.
// Returns a *NotFoundError when no entities are found.
func (acq *ApexCustomerQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = acq.Limit(2).IDs(setContextOp(ctx, acq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apexcustomer.Label}
	default:
		err = &NotSingularError{apexcustomer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (acq *ApexCustomerQuery) OnlyIDX(ctx context.Context) string {
	id, err := acq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApexCustomers.
func (acq *ApexCustomerQuery) All(ctx context.Context) ([]*ApexCustomer, error) {
	ctx = setContextOp(ctx, acq.ctx, "All")
	if err := acq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApexCustomer, *ApexCustomerQuery]()
	return withInterceptors[[]*ApexCustomer](ctx, acq, qr, acq.inters)
}

// AllX is like All, but panics if an error occurs.
func (acq *ApexCustomerQuery) AllX(ctx context.Context) []*ApexCustomer {
	nodes, err := acq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApexCustomer IDs.
func (acq *ApexCustomerQuery) IDs(ctx context.Context) (ids []string, err error) {
	if acq.ctx.Unique == nil && acq.path != nil {
		acq.Unique(true)
	}
	ctx = setContextOp(ctx, acq.ctx, "IDs")
	if err = acq.Select(apexcustomer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (acq *ApexCustomerQuery) IDsX(ctx context.Context) []string {
	ids, err := acq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (acq *ApexCustomerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, acq.ctx, "Count")
	if err := acq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, acq, querierCount[*ApexCustomerQuery](), acq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (acq *ApexCustomerQuery) CountX(ctx context.Context) int {
	count, err := acq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (acq *ApexCustomerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, acq.ctx, "Exist")
	switch _, err := acq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entities: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (acq *ApexCustomerQuery) ExistX(ctx context.Context) bool {
	exist, err := acq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApexCustomerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (acq *ApexCustomerQuery) Clone() *ApexCustomerQuery {
	if acq == nil {
		return nil
	}
	return &ApexCustomerQuery{
		config:         acq.config,
		ctx:            acq.ctx.Clone(),
		order:          append([]apexcustomer.OrderOption{}, acq.order...),
		inters:         append([]Interceptor{}, acq.inters...),
		predicates:     append([]predicate.ApexCustomer{}, acq.predicates...),
		withIdentities: acq.withIdentities.Clone(),
		// clone intermediate query.
		sql:  acq.sql.Clone(),
		path: acq.path,
	}
}

// WithIdentities tells the query-builder to eager-load the nodes that are connected to
// the "identities" edge. The optional arguments are used to configure the query builder of the edge.
func (acq *ApexCustomerQuery) WithIdentities(opts ...func(*ApexCustomerIdentityQuery)) *ApexCustomerQuery {
	query := (&ApexCustomerIdentityClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	acq.withIdentities = query
	return acq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApexCustomer.Query().
//		GroupBy(apexcustomer.FieldCreatedAt).
//		Aggregate(entities.Count()).
//		Scan(ctx, &v)
func (acq *ApexCustomerQuery) GroupBy(field string, fields ...string) *ApexCustomerGroupBy {
	acq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApexCustomerGroupBy{build: acq}
	grbuild.flds = &acq.ctx.Fields
	grbuild.label = apexcustomer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ApexCustomer.Query().
//		Select(apexcustomer.FieldCreatedAt).
//		Scan(ctx, &v)
func (acq *ApexCustomerQuery) Select(fields ...string) *ApexCustomerSelect {
	acq.ctx.Fields = append(acq.ctx.Fields, fields...)
	sbuild := &ApexCustomerSelect{ApexCustomerQuery: acq}
	sbuild.label = apexcustomer.Label
	sbuild.flds, sbuild.scan = &acq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApexCustomerSelect configured with the given aggregations.
func (acq *ApexCustomerQuery) Aggregate(fns ...AggregateFunc) *ApexCustomerSelect {
	return acq.Select().Aggregate(fns...)
}

func (acq *ApexCustomerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range acq.inters {
		if inter == nil {
			return fmt.Errorf("entities: uninitialized interceptor (forgotten import entities/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, acq); err != nil {
				return err
			}
		}
	}
	for _, f := range acq.ctx.Fields {
		if !apexcustomer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entities: invalid field %q for query", f)}
		}
	}
	if acq.path != nil {
		prev, err := acq.path(ctx)
		if err != nil {
			return err
		}
		acq.sql = prev
	}
	return nil
}

func (acq *ApexCustomerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApexCustomer, error) {
	var (
		nodes       = []*ApexCustomer{}
		_spec       = acq.querySpec()
		loadedTypes = [1]bool{
			acq.withIdentities != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApexCustomer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApexCustomer{config: acq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = acq.schemaConfig.ApexCustomer
	ctx = internal.NewSchemaConfigContext(ctx, acq.schemaConfig)
	if len(acq.modifiers) > 0 {
		_spec.Modifiers = acq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, acq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := acq.withIdentities; query != nil {
		if err := acq.loadIdentities(ctx, query, nodes,
			func(n *ApexCustomer) { n.Edges.Identities = []*ApexCustomerIdentity{} },
			func(n *ApexCustomer, e *ApexCustomerIdentity) { n.Edges.Identities = append(n.Edges.Identities, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range acq.withNamedIdentities {
		if err := acq.loadIdentities(ctx, query, nodes,
			func(n *ApexCustomer) { n.appendNamedIdentities(name) },
			func(n *ApexCustomer, e *ApexCustomerIdentity) { n.appendNamedIdentities(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range acq.loadTotal {
		if err := acq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (acq *ApexCustomerQuery) loadIdentities(ctx context.Context, query *ApexCustomerIdentityQuery, nodes []*ApexCustomer, init func(*ApexCustomer), assign func(*ApexCustomer, *ApexCustomerIdentity)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*ApexCustomer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ApexCustomerIdentity(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(apexcustomer.IdentitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.apex_customer_identities
		if fk == nil {
			return fmt.Errorf(`foreign-key "apex_customer_identities" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "apex_customer_identities" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (acq *ApexCustomerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := acq.querySpec()
	_spec.Node.Schema = acq.schemaConfig.ApexCustomer
	ctx = internal.NewSchemaConfigContext(ctx, acq.schemaConfig)
	if len(acq.modifiers) > 0 {
		_spec.Modifiers = acq.modifiers
	}
	_spec.Node.Columns = acq.ctx.Fields
	if len(acq.ctx.Fields) > 0 {
		_spec.Unique = acq.ctx.Unique != nil && *acq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, acq.driver, _spec)
}

func (acq *ApexCustomerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(apexcustomer.Table, apexcustomer.Columns, sqlgraph.NewFieldSpec(apexcustomer.FieldID, field.TypeString))
	_spec.From = acq.sql
	if unique := acq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if acq.path != nil {
		_spec.Unique = true
	}
	if fields := acq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apexcustomer.FieldID)
		for i := range fields {
			if fields[i] != apexcustomer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := acq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := acq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := acq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := acq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (acq *ApexCustomerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(acq.driver.Dialect())
	t1 := builder.Table(apexcustomer.Table)
	columns := acq.ctx.Fields
	if len(columns) == 0 {
		columns = apexcustomer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if acq.sql != nil {
		selector = acq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if acq.ctx.Unique != nil && *acq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(acq.schemaConfig.ApexCustomer)
	ctx = internal.NewSchemaConfigContext(ctx, acq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range acq.modifiers {
		m(selector)
	}
	for _, p := range acq.predicates {
		p(selector)
	}
	for _, p := range acq.order {
		p(selector)
	}
	if offset := acq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := acq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (acq *ApexCustomerQuery) ForUpdate(opts ...sql.LockOption) *ApexCustomerQuery {
	if acq.driver.Dialect() == dialect.Postgres {
		acq.Unique(false)
	}
	acq.modifiers = append(acq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return acq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (acq *ApexCustomerQuery) ForShare(opts ...sql.LockOption) *ApexCustomerQuery {
	if acq.driver.Dialect() == dialect.Postgres {
		acq.Unique(false)
	}
	acq.modifiers = append(acq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return acq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (acq *ApexCustomerQuery) Modify(modifiers ...func(s *sql.Selector)) *ApexCustomerSelect {
	acq.modifiers = append(acq.modifiers, modifiers...)
	return acq.Select()
}

// WithNamedIdentities tells the query-builder to eager-load the nodes that are connected to the "identities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (acq *ApexCustomerQuery) WithNamedIdentities(name string, opts ...func(*ApexCustomerIdentityQuery)) *ApexCustomerQuery {
	query := (&ApexCustomerIdentityClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if acq.withNamedIdentities == nil {
		acq.withNamedIdentities = make(map[string]*ApexCustomerIdentityQuery)
	}
	acq.withNamedIdentities[name] = query
	return acq
}

// ApexCustomerGroupBy is the group-by builder for ApexCustomer entities.
type ApexCustomerGroupBy struct {
	selector
	build *ApexCustomerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (acgb *ApexCustomerGroupBy) Aggregate(fns ...AggregateFunc) *ApexCustomerGroupBy {
	acgb.fns = append(acgb.fns, fns...)
	return acgb
}

// Scan applies the selector query and scans the result into the given value.
func (acgb *ApexCustomerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acgb.build.ctx, "GroupBy")
	if err := acgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApexCustomerQuery, *ApexCustomerGroupBy](ctx, acgb.build, acgb, acgb.build.inters, v)
}

func (acgb *ApexCustomerGroupBy) sqlScan(ctx context.Context, root *ApexCustomerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(acgb.fns))
	for _, fn := range acgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*acgb.flds)+len(acgb.fns))
		for _, f := range *acgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*acgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApexCustomerSelect is the builder for selecting fields of ApexCustomer entities.
type ApexCustomerSelect struct {
	*ApexCustomerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (acs *ApexCustomerSelect) Aggregate(fns ...AggregateFunc) *ApexCustomerSelect {
	acs.fns = append(acs.fns, fns...)
	return acs
}

// Scan applies the selector query and scans the result into the given value.
func (acs *ApexCustomerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acs.ctx, "Select")
	if err := acs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApexCustomerQuery, *ApexCustomerSelect](ctx, acs.ApexCustomerQuery, acs, acs.inters, v)
}

func (acs *ApexCustomerSelect) sqlScan(ctx context.Context, root *ApexCustomerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(acs.fns))
	for _, fn := range acs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*acs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (acs *ApexCustomerSelect) Modify(modifiers ...func(s *sql.Selector)) *ApexCustomerSelect {
	acs.modifiers = append(acs.modifiers, modifiers...)
	return acs
}
