// Code generated by ent, DO NOT EDIT.

package entities

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (ac *ApexCustomer) Identities(ctx context.Context) (result []*ApexCustomerIdentity, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = ac.NamedIdentities(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = ac.Edges.IdentitiesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = ac.QueryIdentities().All(ctx)
	}
	return result, err
}

func (aci *ApexCustomerIdentity) Customer(ctx context.Context) (*ApexCustomer, error) {
	result, err := aci.Edges.CustomerOrErr()
	if IsNotLoaded(err) {
		result, err = aci.QueryCustomer().Only(ctx)
	}
	return result, err
}
