// Code generated by ent, DO NOT EDIT.

package entities

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sigmasee/sigmasee/customer/shared/entities/customer"
	"github.com/sigmasee/sigmasee/customer/shared/entities/customersetting"
)

// CustomerSettingCreate is the builder for creating a CustomerSetting entity.
type CustomerSettingCreate struct {
	config
	mutation *CustomerSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (csc *CustomerSettingCreate) SetCreatedAt(t time.Time) *CustomerSettingCreate {
	csc.mutation.SetCreatedAt(t)
	return csc
}

// SetModifiedAt sets the "modified_at" field.
func (csc *CustomerSettingCreate) SetModifiedAt(t time.Time) *CustomerSettingCreate {
	csc.mutation.SetModifiedAt(t)
	return csc
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (csc *CustomerSettingCreate) SetNillableModifiedAt(t *time.Time) *CustomerSettingCreate {
	if t != nil {
		csc.SetModifiedAt(*t)
	}
	return csc
}

// SetDeletedAt sets the "deleted_at" field.
func (csc *CustomerSettingCreate) SetDeletedAt(t time.Time) *CustomerSettingCreate {
	csc.mutation.SetDeletedAt(t)
	return csc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (csc *CustomerSettingCreate) SetNillableDeletedAt(t *time.Time) *CustomerSettingCreate {
	if t != nil {
		csc.SetDeletedAt(*t)
	}
	return csc
}

// SetID sets the "id" field.
func (csc *CustomerSettingCreate) SetID(s string) *CustomerSettingCreate {
	csc.mutation.SetID(s)
	return csc
}

// SetCustomerID sets the "customer" edge to the Customer entity by ID.
func (csc *CustomerSettingCreate) SetCustomerID(id string) *CustomerSettingCreate {
	csc.mutation.SetCustomerID(id)
	return csc
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (csc *CustomerSettingCreate) SetCustomer(c *Customer) *CustomerSettingCreate {
	return csc.SetCustomerID(c.ID)
}

// Mutation returns the CustomerSettingMutation object of the builder.
func (csc *CustomerSettingCreate) Mutation() *CustomerSettingMutation {
	return csc.mutation
}

// Save creates the CustomerSetting in the database.
func (csc *CustomerSettingCreate) Save(ctx context.Context) (*CustomerSetting, error) {
	return withHooks(ctx, csc.sqlSave, csc.mutation, csc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csc *CustomerSettingCreate) SaveX(ctx context.Context) *CustomerSetting {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csc *CustomerSettingCreate) Exec(ctx context.Context) error {
	_, err := csc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csc *CustomerSettingCreate) ExecX(ctx context.Context) {
	if err := csc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csc *CustomerSettingCreate) check() error {
	if _, ok := csc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`entities: missing required field "CustomerSetting.created_at"`)}
	}
	if _, ok := csc.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer", err: errors.New(`entities: missing required edge "CustomerSetting.customer"`)}
	}
	return nil
}

func (csc *CustomerSettingCreate) sqlSave(ctx context.Context) (*CustomerSetting, error) {
	if err := csc.check(); err != nil {
		return nil, err
	}
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CustomerSetting.ID type: %T", _spec.ID.Value)
		}
	}
	csc.mutation.id = &_node.ID
	csc.mutation.done = true
	return _node, nil
}

func (csc *CustomerSettingCreate) createSpec() (*CustomerSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomerSetting{config: csc.config}
		_spec = sqlgraph.NewCreateSpec(customersetting.Table, sqlgraph.NewFieldSpec(customersetting.FieldID, field.TypeString))
	)
	_spec.Schema = csc.schemaConfig.CustomerSetting
	_spec.OnConflict = csc.conflict
	if id, ok := csc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := csc.mutation.CreatedAt(); ok {
		_spec.SetField(customersetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := csc.mutation.ModifiedAt(); ok {
		_spec.SetField(customersetting.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if value, ok := csc.mutation.DeletedAt(); ok {
		_spec.SetField(customersetting.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if nodes := csc.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   customersetting.CustomerTable,
			Columns: []string{customersetting.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		edge.Schema = csc.schemaConfig.CustomerSetting
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.customer_customer_settings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomerSetting.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerSettingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (csc *CustomerSettingCreate) OnConflict(opts ...sql.ConflictOption) *CustomerSettingUpsertOne {
	csc.conflict = opts
	return &CustomerSettingUpsertOne{
		create: csc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomerSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (csc *CustomerSettingCreate) OnConflictColumns(columns ...string) *CustomerSettingUpsertOne {
	csc.conflict = append(csc.conflict, sql.ConflictColumns(columns...))
	return &CustomerSettingUpsertOne{
		create: csc,
	}
}

type (
	// CustomerSettingUpsertOne is the builder for "upsert"-ing
	//  one CustomerSetting node.
	CustomerSettingUpsertOne struct {
		create *CustomerSettingCreate
	}

	// CustomerSettingUpsert is the "OnConflict" setter.
	CustomerSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *CustomerSettingUpsert) SetCreatedAt(v time.Time) *CustomerSettingUpsert {
	u.Set(customersetting.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CustomerSettingUpsert) UpdateCreatedAt() *CustomerSettingUpsert {
	u.SetExcluded(customersetting.FieldCreatedAt)
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *CustomerSettingUpsert) SetModifiedAt(v time.Time) *CustomerSettingUpsert {
	u.Set(customersetting.FieldModifiedAt, v)
	return u
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *CustomerSettingUpsert) UpdateModifiedAt() *CustomerSettingUpsert {
	u.SetExcluded(customersetting.FieldModifiedAt)
	return u
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *CustomerSettingUpsert) ClearModifiedAt() *CustomerSettingUpsert {
	u.SetNull(customersetting.FieldModifiedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomerSettingUpsert) SetDeletedAt(v time.Time) *CustomerSettingUpsert {
	u.Set(customersetting.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomerSettingUpsert) UpdateDeletedAt() *CustomerSettingUpsert {
	u.SetExcluded(customersetting.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomerSettingUpsert) ClearDeletedAt() *CustomerSettingUpsert {
	u.SetNull(customersetting.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CustomerSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customersetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerSettingUpsertOne) UpdateNewValues() *CustomerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(customersetting.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomerSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomerSettingUpsertOne) Ignore() *CustomerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerSettingUpsertOne) DoNothing() *CustomerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerSettingCreate.OnConflict
// documentation for more info.
func (u *CustomerSettingUpsertOne) Update(set func(*CustomerSettingUpsert)) *CustomerSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CustomerSettingUpsertOne) SetCreatedAt(v time.Time) *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CustomerSettingUpsertOne) UpdateCreatedAt() *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *CustomerSettingUpsertOne) SetModifiedAt(v time.Time) *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *CustomerSettingUpsertOne) UpdateModifiedAt() *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.UpdateModifiedAt()
	})
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *CustomerSettingUpsertOne) ClearModifiedAt() *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.ClearModifiedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomerSettingUpsertOne) SetDeletedAt(v time.Time) *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomerSettingUpsertOne) UpdateDeletedAt() *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomerSettingUpsertOne) ClearDeletedAt() *CustomerSettingUpsertOne {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *CustomerSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("entities: missing options for CustomerSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomerSettingUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("entities: CustomerSettingUpsertOne.ID is not supported by MySQL driver. Use CustomerSettingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomerSettingUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomerSettingCreateBulk is the builder for creating many CustomerSetting entities in bulk.
type CustomerSettingCreateBulk struct {
	config
	err      error
	builders []*CustomerSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomerSetting entities in the database.
func (cscb *CustomerSettingCreateBulk) Save(ctx context.Context) ([]*CustomerSetting, error) {
	if cscb.err != nil {
		return nil, cscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*CustomerSetting, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *CustomerSettingCreateBulk) SaveX(ctx context.Context) []*CustomerSetting {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cscb *CustomerSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := cscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cscb *CustomerSettingCreateBulk) ExecX(ctx context.Context) {
	if err := cscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomerSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerSettingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (cscb *CustomerSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomerSettingUpsertBulk {
	cscb.conflict = opts
	return &CustomerSettingUpsertBulk{
		create: cscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomerSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cscb *CustomerSettingCreateBulk) OnConflictColumns(columns ...string) *CustomerSettingUpsertBulk {
	cscb.conflict = append(cscb.conflict, sql.ConflictColumns(columns...))
	return &CustomerSettingUpsertBulk{
		create: cscb,
	}
}

// CustomerSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomerSetting nodes.
type CustomerSettingUpsertBulk struct {
	create *CustomerSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomerSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customersetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerSettingUpsertBulk) UpdateNewValues() *CustomerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(customersetting.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomerSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomerSettingUpsertBulk) Ignore() *CustomerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerSettingUpsertBulk) DoNothing() *CustomerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerSettingCreateBulk.OnConflict
// documentation for more info.
func (u *CustomerSettingUpsertBulk) Update(set func(*CustomerSettingUpsert)) *CustomerSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CustomerSettingUpsertBulk) SetCreatedAt(v time.Time) *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CustomerSettingUpsertBulk) UpdateCreatedAt() *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *CustomerSettingUpsertBulk) SetModifiedAt(v time.Time) *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *CustomerSettingUpsertBulk) UpdateModifiedAt() *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.UpdateModifiedAt()
	})
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *CustomerSettingUpsertBulk) ClearModifiedAt() *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.ClearModifiedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomerSettingUpsertBulk) SetDeletedAt(v time.Time) *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomerSettingUpsertBulk) UpdateDeletedAt() *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomerSettingUpsertBulk) ClearDeletedAt() *CustomerSettingUpsertBulk {
	return u.Update(func(s *CustomerSettingUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *CustomerSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("entities: OnConflict was set for builder %d. Set it on the CustomerSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("entities: missing options for CustomerSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
