// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// CustomerOutbox is the predicate function for customeroutbox builders.
type CustomerOutbox func(*sql.Selector)

// CustomerSetting is the predicate function for customersetting builders.
type CustomerSetting func(*sql.Selector)

// Identity is the predicate function for identity builders.
type Identity func(*sql.Selector)
