app:
  listeningInterface: ":10000"
  domainSource: "urn::sigmasee::customer"
  appSource: "customer-api"
  baseDomain: "http://localhost:15000"

postgres:
  connectionString: "postgres://root@cockroachdb.localhost:26257/customer"
  maxOpenConnections: 100

kafka:
  bootstrapServers: kafka.localhost:19092
  enableTls: false
  enableSasl: false

outbox:
  maxRetryCount: 30
  retryDelay: 10s

cognitoIdentityProvider:
  refreshRsaKeys: true

googleIdentityProvider:
  refreshRsaKeys: true

slackIdentityProvider:
  refreshRsaKeys: true
