// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApexCustomer is the predicate function for apexcustomer builders.
type ApexCustomer func(*sql.Selector)

// ApexCustomerIdentity is the predicate function for apexcustomeridentity builders.
type ApexCustomerIdentity func(*sql.Selector)
