// Code generated by sigmaseectl, DO NOT EDIT.

package v1

import (
	_ "embed"
)

const TopicName = "customer.v1.event"
const RetryTopicNamePrefix = "customer.v1.event.retry"
const RetryTopicNameCount = 1
const DeadLetterTopicName = "customer.v1.event.deadletter"

//go:embed schema/schema.proto
var protobuf string

func GetProtobufSchema() string {
	return protobuf
}
