// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package appsetup

import (
	"github.com/sigmasee/sigmasee/apex/apex-api/http"
	"github.com/sigmasee/sigmasee/apex/apex-api/openapi"
	"github.com/sigmasee/sigmasee/apex/shared/repositories"
	"github.com/sigmasee/sigmasee/shared/enterprise/configuration"
	"github.com/sigmasee/sigmasee/shared/enterprise/security/token"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewHttpServer(logger *zap.SugaredLogger, appConfig configuration.AppConfig, entgoClient repositories.EntgoClient, tokenService token.TokenService) (http.HttpServer, error) {
	openApiApexV1, err := openapi.NewOpenApiApexV1(logger)
	if err != nil {
		return nil, err
	}
	httpServer, err := http.NewHttpServer(logger, appConfig, openApiApexV1)
	if err != nil {
		return nil, err
	}
	return httpServer, nil
}
